### ISSUE TITLE
Remove trailing white spaces from connection type

### ISSUE THREAD

**Issue by Crosswind** [ibm-messaging/mq-smf-csv#1]
Hey,

First of all, thank you for this amazing tool and open sourcing it! I wish there was more SMF analysers out there which enable working with SMF in general (without trying to do much of analysis magic itself).

I've stumbled across a minor issue that I'd like to address as others may have similar issues.

For some reasons some connection types have a trailing white space. This is inserted into all the reports in the respective column and can lead to errors e.g., when selecting all Appl_Type = "TSO" you have to either strip() the contents first or match with "TSO " (notice the blank). It is inconsistent throughout the different types.

https://github.com/ibm-messaging/mq-smf-csv/blob/d808420c7fa6723cdb3f5a391fcb6a640f1dbd1d/src/smfConv.c#L290-L296

I would like to have these white spaces removed as - from my point of view - adds more confusion that has functionality. Is there any rationale in having these trailing white spaces for some connection types that needs to be considered?

Since this is a minor code change I haven't created a PR because it requires to create a new version and I'm not sure if this is reasonable in this case. It is likely to make more sense to - if accepted - include this change in an upcoming release. If it is okay to have a separate release (supposedly v5.4.6) for this I would be happy to create the PR.

Cheers - David

**Comment by ibmmqmet** [comment]
Thanks for noticing that. Noone has previously - probably noone's tried to filter/select on that field.

As you may know, there's a new version of MQ being released imminently. And there will have to be a new level of this package to recognise the new SMF metric available. So I'll patch up the ApplType at that point.

**Comment by Crosswind** [comment]
I have only heard about the new Multiplatform release but I figured a z/OS release wouldn't be far away. Sounds good and I'll look forward to that. Feel free to do with this issue whatever you like - you can close it immediately or whenever you have this patched in the next release.

**Comment by Crosswind** [comment]
Thanks for including the change in the current release. I am also closing this issue.
